### ISSUE TITLE
feat: 아고라 UI 정적 화면 구성

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-frontend#2]
## Description
사용자가 보게 될 정적인 화면 구현

## Tasks

- [x] UI 컴포넌트 구현
- [x] 웹 접근성을 위해 색 명암, 접근성 트리 고려
- [x] 다크 모드 추가

## 기대 효과
- 웹 접근성을 통해 모두에게 동일한 서비스 제공
- 다크 모드로 눈의 피로감 감소

## References
- [다크 모드](https://blog.naver.com/cick3105/222058502102)
- [카카오 모두를 위한 웹 접근성](https://tech.kakaopay.com/post/accessibility-stories-for-everyone/)
